# Game of Thrones

Are you a fan of the Game of Thrones series? Let's test it. Let's use the API: <a href="https://anapioficeandfire.com/" target="_blank">https://anapioficeandfire.com/</a> to find out more about the series.

In [1]:
import sys
print(sys.executable)

/Users/olivierkdw/projets/.venv/bin/python

1. Import the following libraries: 

      * ```requests```
      * ```pandas```
      * ```json```

In [2]:
import requests
import pandas as pd
import json

2. Go to the URL indicated in the description above. Using `requests`, get data on a character in the series. It doesn't matter who the character is.

In [40]:
url = "https://anapioficeandfire.com/api/characters/2"
r = requests.get(url)
print(r.content)

b'{"url":"https://anapioficeandfire.com/api/characters/2","name":"Walder","gender":"Male","culture":"","born":"","died":"","titles":[],"aliases":["Hodor"],"father":"","mother":"","spouse":"","allegiances":["https://anapioficeandfire.com/api/houses/362"],"books":["https://anapioficeandfire.com/api/books/1","https://anapioficeandfire.com/api/books/2","https://anapioficeandfire.com/api/books/3","https://anapioficeandfire.com/api/books/5","https://anapioficeandfire.com/api/books/8"],"povBooks":[],"tvSeries":["Season 1","Season 2","Season 3","Season 4","Season 6"],"playedBy":["Kristian Nairn"]}'

3. Extract these data in JSON format:

In [42]:
data = r.json() # transforme la réponse API en dictionnaire Python
print(data)

{'url': 'https://anapioficeandfire.com/api/characters/2', 'name': 'Walder', 'gender': 'Male', 'culture': '', 'born': '', 'died': '', 'titles': [], 'aliases': ['Hodor'], 'father': '', 'mother': '', 'spouse': '', 'allegiances': ['https://anapioficeandfire.com/api/houses/362'], 'books': ['https://anapioficeandfire.com/api/books/1', 'https://anapioficeandfire.com/api/books/2', 'https://anapioficeandfire.com/api/books/3', 'https://anapioficeandfire.com/api/books/5', 'https://anapioficeandfire.com/api/books/8'], 'povBooks': [], 'tvSeries': ['Season 1', 'Season 2', 'Season 3', 'Season 4', 'Season 6'], 'playedBy': ['Kristian Nairn']}

In [43]:
print(type(data))

<class 'dict'>

In [ ]:
# data[0]["gender"]

KeyError: 0

In [31]:
# df_normalize = pd.json_normalize(data)
# df_normalize.head()

In [14]:
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)
# df_normalize.head()

,url,name,gender,culture,born,died,titles,aliases,father,mother,spouse,allegiances,books,povBooks,tvSeries,playedBy
0,https://anapioficeandfire.com/api/characters/2,Walder,Male,,,,[],[Hodor],,,,[https://anapioficeandfire.com/api/houses/362],"[https://anapioficeandfire.com/api/books/1, ht...",[],"[Season 1, Season 2, Season 3, Season 4, Seaso...",[Kristian Nairn]

4. Now extract the JSON keys you have obtained and create a DataFrame that will have the JSON keys you extracted as a column.

**Hint**: we can use: `r.json().keys()`.

In [45]:
columns = list(r.json().keys())
print(columns)

['url', 'name', 'gender', 'culture', 'born', 'died', 'titles', 'aliases', 'father', 'mother', 'spouse', 'allegiances', 'books', 'povBooks', 'tvSeries', 'playedBy']

# Rappel des arguments possibles de pd.Dataframe
pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)
EX1 : créer un df vide avec colonnes définies -> df = pd.DataFrame(columns=['name', 'gender', 'culture'])
print(df)

EX2 : Je peux réordonnancer les colonnes même si data était dans le désordre -> 
data = {'gender': ['Male'], 'name': ['Jon'], 'culture' ['Northmen']}
df = pd.DataFrame(data, columns=['name', 'gender', 'culture'])
print(df)

EX3 : Je peux ajouter à la volée des colonnes absentes initialement ->
data = {'name': ['Arya']}
df = pd.DataFrame(data, columns=['name', 'gender', 'age'])

EX4 : data est une liste de dictionnaires -> pas besoin de préciser l'argument columns
data = [
    {'name': 'Jon', 'gender': 'Male'},
    {'name': 'Arya', 'gender': 'Female'}
]
df = pd.DataFrame(data)

EX5 : data est un dictionnaire de liste -> pas besoin de préciser l'argument columns
data = {
    'name': ['Jon', 'Arya'],
    'gender': ['Male', 'Female']
}
df = pd.DataFrame(data)

EX6 : data est une liste de listes -> auquel cas préciser l'argument columns!
data = [
    ['Jon', 'Male'],
    ['Arya', 'Female']
]
df = pd.DataFrame(data, columns=['name', 'gender'])

In [46]:
df = pd.DataFrame(columns=columns)
df

Empty DataFrame
Columns: [url, name, gender, culture, born, died, titles, aliases, father, mother, spouse, allegiances, books, povBooks, tvSeries, playedBy]
Index: []

5. Create a loop to extract data from the firsts 150 characters of the series and add them to your DataFrame.

In [48]:
base_url = "https://anapioficeandfire.com/api/characters/"
df = pd.DataFrame(columns=columns) # df vide
# les index du df iront de 0 à 149


for i in range(1, 151): # 151 exclu
    r = requests.get(base_url + str(i)) # concatenation des chaînes 
    # r= https://anapioficeandfire.com/api/characters/1

    data = r.json() # 
    df.loc[len(df)] = data 
    
    # Pour chaque colonne du DataFrame :
    # df.loc[index, colonne] = dict.get(colonne, NaN)
    
    # pandas va lire les colonnes du Df -> pour chacune
    # il cherche dict["colonne"]
    #si elle existe → il met la valeur
    #si elle n'existe pas → il met NaN


    # SI LES NOMS NE CORRESPONDENT PAS → 
    # pandas crée de NOUVELLES COLONNES
    # mais ici columns est extrait de la réponse API (sans objet)
    print(f"{i} personnage done")

1 personnage done
2 personnage done
3 personnage done
4 personnage done
5 personnage done
6 personnage done
7 personnage done
8 personnage done
9 personnage done
10 personnage done
11 personnage done
12 personnage done
13 personnage done
14 personnage done
15 personnage done
16 personnage done
17 personnage done
18 personnage done
19 personnage done
20 personnage done
21 personnage done
22 personnage done
23 personnage done
24 personnage done
25 personnage done
26 personnage done
27 personnage done
28 personnage done
29 personnage done
30 personnage done
31 personnage done
32 personnage done
33 personnage done
34 personnage done
35 personnage done
36 personnage done
37 personnage done
38 personnage done
39 personnage done
40 personnage done
41 personnage done
42 personnage done
43 personnage done
44 personnage done
45 personnage done
46 personnage done
47 personnage done
48 personnage done
49 personnage done
50 personnage done
51 personnage done
52 personnage done
53 personnage done
54 personnage done
55 personnage done
56 personnage done
57 personnage done
58 personnage done
59 personnage done
60 personnage done
61 personnage done
62 personnage done
63 personnage done
64 personnage done
65 personnage done
66 personnage done
67 personnage done
68 personnage done
69 personnage done
70 personnage done
71 personnage done
72 personnage done
73 personnage done
74 personnage done
75 personnage done
76 personnage done
77 personnage done
78 personnage done
79 personnage done
80 personnage done
81 personnage done
82 personnage done
83 personnage done
84 personnage done
85 personnage done
86 personnage done
87 personnage done
88 personnage done
89 personnage done
90 personnage done
91 personnage done
92 personnage done
93 personnage done
94 personnage done
95 personnage done
96 personnage done
97 personnage done
98 personnage done
99 personnage done
100 personnage done
101 personnage done
102 personnage done
103 personnage done
104 personnage done
105 personnage done
106 personnage done
107 personnage done
108 personnage done
109 personnage done
110 personnage done
111 personnage done
112 personnage done
113 personnage done
114 personnage done
115 personnage done
116 personnage done
117 personnage done
118 personnage done
119 personnage done
120 personnage done
121 personnage done
122 personnage done
123 personnage done
124 personnage done
125 personnage done
126 personnage done
127 personnage done
128 personnage done
129 personnage done
130 personnage done
131 personnage done
132 personnage done
133 personnage done
134 personnage done
135 personnage done
136 personnage done
137 personnage done
138 personnage done
139 personnage done
140 personnage done
141 personnage done
142 personnage done
143 personnage done
144 personnage done
145 personnage done
146 personnage done
147 personnage done
148 personnage done
149 personnage done
150 personnage done

In [47]:
df.head()

Empty DataFrame
Columns: [url, name, gender, culture, born, died, titles, aliases, father, mother, spouse, allegiances, books, povBooks, tvSeries, playedBy]
Index: []